# DefaultPawnClass: ADefaultPawn = fly spectator; ACharacter = ground XZ movement
[/Script/Sandbox.GameMode]
GameModeClass=ASandboxGameMode
DefaultPawnClass=ADefaultPawn
PlayerControllerClass=APlayerController
HUDClass=ASandboxHUD
GameStateClass=AGameStateBase
PlayerStateClass=APlayerState

[/Script/Engine.GameModeBase]
DefaultPawnClass=ADefaultPawn
PlayerControllerClass=APlayerController
HUDClass=AHUD
GameStateClass=AGameStateBase
PlayerStateClass=APlayerState
