#pragma once

// Core Engine Services
#include "core/Application.hpp"
#include "core/Base.hpp"
#include "core/ConfigFile.hpp"
#include "core/events/ApplicationEvent.hpp"
#include "core/events/Event.hpp"
#include "core/events/KeyEvent.hpp"
#include "core/events/MouseEvent.hpp"
#include "core/Input.hpp"
#include "core/Layer.hpp"
#include "core/Log.hpp"
#include "core/Timestep.hpp"
#include "core/UEngine.hpp"
#include "core/Window.hpp"

// Unreal Gameplay Framework
#include "gameplay/AActor.hpp"
#include "gameplay/ACameraActor.hpp"
#include "gameplay/ADefaultPawn.hpp"
#include "gameplay/AGameModeBase.hpp"
#include "gameplay/AGameStateBase.hpp"
#include "gameplay/APawn.hpp"
#include "gameplay/APlayerCameraManager.hpp"
#include "gameplay/APlayerController.hpp"
#include "gameplay/APlayerState.hpp"
#include "gameplay/UClassRegistry.hpp"
#include "gameplay/UObject.hpp"

// World & Serialization
#include "world/Components.hpp"
#include "world/MapSerializer.hpp"
#include "world/MaterialSerializer.hpp"
#include "world/UGameInstance.hpp"
#include "world/UWorld.hpp"

// Renderer & Assets
#include "renderer/AssetManager.hpp"
#include "renderer/Buffer.hpp"
#include "renderer/Framebuffer.hpp"
#include "renderer/GraphicsContext.hpp"
#include "renderer/IBLGenerator.hpp"
#include "renderer/Light.hpp"
#include "renderer/Material.hpp"
#include "renderer/MaterialInstance.hpp"
#include "renderer/MeshPrimitives.hpp"
#include "renderer/PerspectiveCamera.hpp"
#include "renderer/PostProcessPipeline.hpp"
#include "renderer/RenderAPI.hpp"
#include "renderer/RenderCommand.hpp"
#include "renderer/Renderer.hpp"
#include "renderer/SceneRenderer.hpp"
#include "renderer/Shader.hpp"
#include "renderer/StaticMesh.hpp"
#include "renderer/TextRenderer.hpp"
#include "renderer/Texture.hpp"
#include "renderer/VertexArray.hpp"
