#pragma once

// Core Engine Services
#include "Core/FApplication.hpp"
#include "Core/Base.hpp"
#include "Core/FConfigFile.hpp"
#include "Core/events/FApplicationEvent.hpp"
#include "Core/events/FEvent.hpp"
#include "Core/events/FKeyEvent.hpp"
#include "Core/events/FMouseEvent.hpp"
#include "Core/FInput.hpp"
#include "Core/FInputSettings.hpp"
#include "Engine/UEngine.hpp"
#include "Core/FWindow.hpp"

// Unreal Gameplay Framework
#include "Gameplay/AActor.hpp"
#include "Gameplay/ACameraActor.hpp"
#include "Gameplay/ACharacter.hpp"
#include "Gameplay/ADefaultPawn.hpp"
#include "Gameplay/AGameModeBase.hpp"
#include "Gameplay/AGameStateBase.hpp"
#include "Gameplay/APawn.hpp"
#include "Gameplay/APlayerCameraManager.hpp"
#include "Gameplay/APlayerController.hpp"
#include "Gameplay/APlayerState.hpp"
#include "Gameplay/AHUD.hpp"
#include "Gameplay/UGameplayStatics.hpp"
#include "Gameplay/UActorComponent.hpp"
#include "Gameplay/UClassRegistry.hpp"
#include "Gameplay/UObject.hpp"

// UI Framework
#include "UMG/UWidget.hpp"
#include "UMG/UPanelWidget.hpp"
#include "UMG/UCanvasPanel.hpp"
#include "UMG/UTextBlock.hpp"
#include "UMG/UButton.hpp"
#include "UMG/UImage.hpp"
#include "UMG/UUserWidget.hpp"
#include "UMG/FUIRenderer.hpp"

// World & Serialization
#include "Engine/Components.hpp"
#include "Engine/FMapSerializer.hpp"
#include "Engine/FMaterialSerializer.hpp"
#include "Engine/UGameInstance.hpp"
#include "Engine/UWorld.hpp"

// Renderer & Assets
#include "Assets/UAssetManager.hpp"
#include "RHI/FBuffer.hpp"
#include "RHI/FFramebuffer.hpp"
#include "RHI/IGraphicsContext.hpp"
#include "Renderer/FIBLGenerator.hpp"
#include "Renderer/FLight.hpp"
#include "Renderer/FMaterial.hpp"
#include "Renderer/FMaterialInstance.hpp"
#include "Renderer/FMeshPrimitives.hpp"
#include "Renderer/FPerspectiveCamera.hpp"
#include "Renderer/FPostProcessPipeline.hpp"
#include "RHI/IRenderAPI.hpp"
#include "RHI/FRenderCommand.hpp"
#include "RHI/FRenderer.hpp"
#include "Renderer/FWorldRenderer.hpp"
#include "RHI/FShader.hpp"
#include "Assets/UStaticMesh.hpp"
#include "Renderer/FTextRenderer.hpp"
#include "RHI/FTexture.hpp"
#include "RHI/FVertexArray.hpp"
